### ISSUE TITLE
Timeout in confirm_eligible

### ISSUE THREAD

**Issue by 1bram** [alfonsrv/impf-botpy#33]
hej, 
i am getting this:

An unexpected exception occurred in <control_main>
Traceback (most recent call last):
  File "/Users/instabilothek/Documents/python/impf-botpy-1/impf/decorators.py", line 63, in func
    return f(self, *args, **kwargs)
  File "/Users/instabilothek/Documents/python/impf-botpy-1/impf/browser.py", line 388, in control_main
    self.confirm_eligible()
  File "/Users/instabilothek/Documents/python/impf-botpy-1/impf/browser.py", line 206, in confirm_eligible
    '//input[@type="radio" and @formcontrolname="isValid"]//following-sibling::span[contains(text(),"Ja")]/..')))
  File "/Users/instabilothek/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

he seems to not be able to find some button..

**Comment by alfonsrv** [comment]
Hey @1bram, thanks for reporting this. Were you able to observe the browser as it happened? I tested this yesterday and it worked without errors.

BR, Alfons

**Comment by 1bram** [comment]
Unfortunately i couldn't observe the browser... hope to see it again later.. will report when i observe it,.

**Comment by alfonsrv** [comment]
Alright! If you happen to see it happen, please make sure to copy the HTML using the `Rightclick` -> `Inspect` functionality rather than `Show source code`, as that will simply load the HTML shell without the executed Javascript.
BR
