### ISSUE TITLE
Geburtsdatum ungueltig oder in der Zukunft

### ISSUE THREAD

**Issue by fgathercoupa** [alfonsrv/impf-botpy#44]
**Describe the issue**
After the latest maintenance window on the impfterminservice server, when trying to obtain a code using /code, I get an error "Geburtsdatum ungueltig oder in der Zukunft". It looks like the api changed a little bit, since there is no option to actually enter a birth date. 

**Versions**
latest

**Log files**

2021-06-03 21:12:26,461 - [INFO] <impf.api.api.py:168>  API: Attempting to get Vermittlungscode from server
2021-06-03 21:12:26,701 - [WARNING] <impf.api.api.py:57>  API: Endpoint returned Error: Geburtsdatum ungueltig oder in der Zukunft
2021-06-03 21:12:26,701 - [INFO] <impf.api.api.py:58>  API: Cookies probably expired – raising AdvancedSessionCache
2021-06-03 21:12:26,702 - [WARNING] <impf.api.decorators.py:133>  API: Underlying service layer indicating invalid session for <generate_vermittlungscode> – refreshing all cookies and retrying
2021-06-03 21:12:28,077 - [INFO] <impf.browser.browser.py:169>  76137: Navigating to ImpfterminService
2021-06-03 21:12:31,724 - [INFO] <impf.browser.browser.py:182>  76137: Selected Bundesland: Baden-Württemberg
2021-06-03 21:12:31,858 - [INFO] <impf.browser.browser.py:190>  76137: Selected Impfzentrum: 76137 Karlsruhe, Kreisimpfzentrum Schwarzwaldhalle Karlsruhe
2021-06-03 21:12:49,104 - [INFO] <impf.api.api.py:168>  API: Attempting to get Vermittlungscode from server
Traceback (most recent call last):
  File "C:\Users\Florian\impfung\impf-botpy\impf\decorators.py", line 131, in func
    x = f(self, *args, **kwargs)
  File "C:\Users\Florian\impfung\impf-botpy\impf\api.py", line 177, in generate_vermittlungscode
    r = self.xs.post(f'{self.host}/rest/smspin/anforderung', json=data)
  File "C:\Users\Florian\impfung\impf-botpy\impf\decorators.py", line 119, in api_response
    x = self._handle_error(response.status_code, response.json())
  File "C:\Users\Florian\impfung\impf-botpy\impf\api.py", line 59, in _handle_error
    raise AdvancedSessionCache(code, message)
kunft'}

Thanks.

**Comment by alfonsrv** [comment]
Hey @fgathercoupa – thanks for the bug report. They indeed changed that part of the website.  
Should be fixed with 7178239. – Can you check if it works for you?

Thanks again, 
Alfons

**Comment by Shirkanesi** [comment]
Seems to end up in another error
[Produced with --code option, normal way not tested bc no slots available]

2021-06-03 23:16:36,586 - [INFO] <impf.api.api.py:130>  API: Potentially missing cookies: ['bm_mi']
2021-06-03 23:16:36,587 - [INFO] <impf.api.api.py:82>  API: Caution! You might not have all cookies to issue requests!
2021-06-03 23:16:37,340 - [INFO] <impf.api.api.py:179>  API: Attempting to get Vermittlungscode from server
Traceback (most recent call last):
  File "D:\DEV\impf-botpy2\main.py", line 117, in <module>
    if args.code: instant_code(); exit()
  File "D:\DEV\impf-botpy2\main.py", line 70, in instant_code
    token = api.generate_vermittlungscode()
  File "D:\DEV\impf-botpy2\impf\decorators.py", line 131, in func
    x = f(self, *args, **kwargs)
  File "D:\DEV\impf-botpy2\impf\api.py", line 192, in generate_vermittlungscode
    self.setup_vermittlungscode(birthday)
  File "D:\DEV\impf-botpy2\impf\decorators.py", line 131, in func
    x = f(self, *args, **kwargs)
  File "D:\DEV\impf-botpy2\impf\api.py", line 173, in setup_vermittlungscode
    r = self.xs.post(f'{self.host}/rest/suche/termincheck/alter', json=data)
  File "D:\DEV\impf-botpy2\impf\decorators.py", line 119, in api_response
    x = self._handle_error(response.status_code, response.json())
  File "D:\DEV\impf-botpy2\impf\api.py", line 54, in _handle_error
    if 'Anfragelimit erreicht' in message.get('error'):
TypeError: argument of type 'NoneType' is not iterable

**Comment by alfonsrv** [comment]
Thanks for the feedback. Unfortunately it seems like they actually hired some software engineers.  

The backend actually checks whether or not vaccine slots are available and now returns `Error from backend: [-1] [{'code': 'WP033', 'text': 'Keine verfügbaren Impfstoffe für die Altersgruppe'}]`.

RIP.

**Comment by Shirkanesi** [comment]
Wow 👏 
Thought this will never happen...
Btw: you should either remove main.py:22 (print(f'- Age: {settings.AGE}')) or add AGE again in the sample config :)

**Comment by alfonsrv** [comment]
Thanks for the pointer.

**Comment by alfonsrv** [comment]
Actually never mind – it still works.

**Comment by Shirkanesi** [comment]
I actually wanted to write that right now xD
Figured it out right now xD

**Comment by DeveloperTK** [comment]
@alfonsrv I don't know if this just happened on accident but at prime hours when many people try to access the website, I get lots of 429 when trying to generate codes. At night when there are no people looking for appointments it mostly just works and doesn't really limit any requests. This would indicate that those requests are (in some ways) not really limited on requests per person but rather on overall traffic. When trying you might have just got unlucky or got rate limited otherwise (the regular rate limit still applies here)

Greetings

**Comment by alfonsrv** [comment]
Well observed – it's true. This is why I added this line: https://github.com/alfonsrv/impf-botpy/blob/main/impf/api.py#L203

However this issue is not related to `429` errors when generating codes.

**Comment by DeveloperTK** [comment]
Ah I see, just one more question: what does `~2345` mean? 😅

**Comment by alfonsrv** [comment]
Approximately 23:45 o'clock. 👀 Read: Twenty-three-hundret-fourty-five – 

as used by US military; it's cool to leave the `:` off the time~

**Comment by alfonsrv** [comment]
But feel free to add a PR if you feel like it should be clearer. Your explanation is actually quite well-worded.

I was just too lazy to bother adding all my lessons learned to the code as print statements or start a FAQ section, as most people don't seem read them anyways.
