### ISSUE TITLE
Remote booking funktioniert nicht

### ISSUE THREAD

**Issue by avierck** [alfonsrv/impf-botpy#54]
Das automatische Buchen (mittels telegram backend) hat heute bei mir nicht funktioniert (manuell zum Glück dann aber doch noch). Fehlermeldung: 

```
2021-06-07 15:36:37,918 - [ERROR] <impf.browser.browser.py:298>  xPLZx: Unexpected exception occurred trying to book appointments remotely!
Traceback (most recent call last):
  File "/Users/xxxxx/dev/impfbot/impf-botpy/impf/browser.py", line 296, in alert_appointment
    self.remote_booking()
  File "/Users/xxxxx/dev/impfbot/impf-botpy/impf/browser.py", line 322, in remote_booking
    if api.book_appointment(appointments, int(_code)) or self.book_appointment(int(_code)):
  File "/Users/xxxxx/dev/impfbot/impf-botpy/impf/decorators.py", line 131, in func
    x = f(self, *args, **kwargs)
  File "/Users/xxxxx/dev/impfbot/impf-botpy/impf/api.py", line 253, in book_appointment
    r = self.xs.post(f'{self.host}/rest/buchung', json=data)
  File "/Users/xxxxx/dev/impfbot/impf-botpy/impf/decorators.py", line 121, in api_response
    return x or api_call(f)(self, *args, **kwargs)
  File "/Users/xxxxx/dev/impfbot/impf-botpy/impf/decorators.py", line 121, in api_response
    return x or api_call(f)(self, *args, **kwargs)
  File "/Users/xxxxx/dev/impfbot/impf-botpy/impf/decorators.py", line 119, in api_response
    x = self._handle_error(response.status_code, response.json())
  File "/Users/xxxxx/dev/impfbot/impf-botpy/impf/api.py", line 45, in _handle_error
    raise AdvancedSessionError(-1, 'Maximum retries exceeded')
impf.exceptions.AdvancedSessionError: [-1] Maximum retries exceeded
2021-06-07 15:36:37,922 - [INFO] <impf.alert.alert.py:62>  Sending alert "Appointment could not be booked – please continue manually!"
```

Kann es sein, dass sich beim Backend auf impfterminservice.de etwas verändert hat? Zumindest sagt mein Browser (nach anmelden mit Code, sonst 401):
`https://229-iz.impfterminservice.de/rest/buchung    404 not found`

**Comment by alfonsrv** [comment]
Hey @avierck – Remote Booking funktioniert weiterhin; gerade getestet. Es gibt allerdings ne ~25%ige Chance, dass du beim Aufruf der Remote Booking API erstmal zum Virtuellen Warteraum weitergeleitet wirst, wodurch der Fehler entsteht. 

BR, Alfons

**Comment by avierck** [comment]
@alfonsrv Ah, okay. Hatte ich mir ja nur so zusammengereimt weil bei allen Zentren die ich getestet hatte ein 404 für `rest/buchung` angezeigt wurde. Hab ja meinen Termin und keinen weiteren Bedarf - dann mach ich mal wieder dicht hier, Danke!
