### ISSUE TITLE
Crash when checking for an appointment with a valid code

### ISSUE THREAD

**Issue by MarcelBochtler** [alfonsrv/impf-botpy#6]
This crash happened for an impfzentrum with a code.
It might be possible that an appointment was available, as other times it doesn't crash while waiting.

```
2021-05-18 19:36:44,941 - [INFO] <impf.browser.browser.py:168>  71636: No longer in waiting room!
2021-05-18 19:37:07,783 - [ERROR] <impf.browser.browser.py:334>  71636: An unexpected exception occurred
Traceback (most recent call last):
  File "/home/marcel/workspace/impf-botpy/impf/browser.py", line 312, in control_main
    if self.code: return self.control_appointment()
  File "/home/marcel/workspace/impf-botpy/impf/browser.py", line 356, in control_appointment
    appointments = self.search_appointments()
  File "/home/marcel/workspace/impf-botpy/impf/browser.py", line 260, in search_appointments
    element = self.driver.find_element_by_xpath('//*[contains(text(), "1. Impftermin")]')
  File "/home/marcel/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/marcel/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/marcel/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/marcel/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), "1. Impftermin")]"}
  (Session info: chrome=90.0.4430.212)

2021-05-18 19:37:07,859 - [INFO] <__main__.main.py:45>  Waiting until 19:42:07 before checking the next location
```

**Comment by alfonsrv** [comment]
Weird. I'm going to wrap this one in a try-catch phrase - just got a confirmation two hours ago, so the code works.  

Your browser possibly got a reply from the server - indicating no appointments were available - too slowly, causing it to jump to the Impftermin-check. Thanks for reporting this.

**Comment by MarcelBochtler** [comment]
> just got a confirmation two hours ago, so the code works.

I also just got a confirmation, so you're correct it works :)
While checking the side manually I got an "unexpected error" at some point as well, so it's also possible that the website wasn't working correctly.

Feel free to close the issue if you're unable to reproduce it.

**Comment by alfonsrv** [comment]
Glad to hear that! I also just pushed a commit 471dbe8 making the bot more resilient against errors caused by human intervention or a spotty server response / slow internet connection. This should prevent the issue from occurring in the future.
